### ISSUE TITLE
docker hub repo

### ISSUE THREAD

**Issue by malishahi** [Reposoft/openidc-keycloak-test#13]
Hi,

Would that be enought to use the docker hub repo?
Or should I use this git repo?

I only want to see if it works.
Tnx.

Are apache, and keycloak installed in one container?

**Comment by solsson** [comment]
I must have missed this question back in March.

Feel free to use https://hub.docker.com/r/solsson/httpd-openidc with your own conf, and the docs at https://github.com/zmartzone/mod_auth_openidc.

The images configured for testing, under ./build-contracts, are not published.
