### ISSUE TITLE
Evaluate private_key_jwt as endpoint auth

### ISSUE THREAD

**Issue by solsson** [Reposoft/openidc-keycloak-test#7]
In #6 I'm unsure which method to prefer in production, of `client_secret_basic` and `client_secret_post`. Or maybe we should try to exemplify `private_key_jwt` in the test config.

**Comment by solsson** [comment]
After mod_auth_openidc 2.0.1 is released, and until this evaluation is done, we can remove the endpoint auth directive from https://github.com/pingidentity/mod_auth_openidc/wiki/Keycloak, thanks to b0b30fe

**Comment by solsson** [comment]
Confirmed again with 2.3.3 that `OIDCProviderTokenEndpointAuth` isn't needed with Keycloak's default settings for confidential OpenID Connect type client.

I have seen it help with a badly configured realm though. But that doesn't fix the root cause :)

**Comment by C0rn3j** [comment]
That wiki page still has the `OIDCProviderTokenEndpointAuth` key value, shouldn't that have been removed?

**Comment by sebix** [comment]
> That wiki page still has the `OIDCProviderTokenEndpointAuth` key value, shouldn't that have been removed?

I just stumbled over this as well and allowed myself to remove it:
https://github.com/OpenIDC/mod_auth_openidc/wiki/Keycloak/_compare/66d0a42ea6867e01baa04a9caed75b5778728ab9...8c4fe1c40f3cb3644747fb7d642bf0cdfa453477
